name: Publish package to GitHub Packages

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm using version from packageManager in package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Setup .npmrc file to publish to GitHub Packages
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Spelling
        run: pnpm run spelling

      - name: Build
        run: pnpm run build

      - name: Publish
        if: success() && github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm publish --access restricted
